spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: "sa"
    password: "sa"
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

springdoc:
  swagger-ui:
    path: /swagger-ui.html

sentry:
  dsn: https://29bff40da20eaf4192bb0c8d86103fcd@o4506270180769792.ingest.sentry.io/4506270199644160
  sentry.traces-sample-rate: 1.0
